### ISSUE TITLE
Organiseren evaluatie BIP en uitkomsten delen

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/BRK-Bevragingen#11]
Input gebruiken bij retrospective sprint 1 of indien nodig eerder

**Comment by fsamwel** [comment]
evaluatie is gepland voor 30 november

**Comment by fsamwel** [comment]
[Evaluatie BRP bevragingen.pptx](https://github.com/VNG-Realisatie/BRK-Bevragingen/files/2653097/Evaluatie.BRP.bevragingen.pptx)
