### ISSUE TITLE
Rekening houden met vragen uit het DSO zoeken en raadplegen (Berni levert specificaties hiervan).

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/BRK-Bevragingen#15]
@JohanBoer Wie is Berni?

**Comment by JanWillemKooi** [comment]
Goede vraag: wie is Berni.

**Comment by TCIMEddy** [comment]
@JanWillemKooi Volgens mij weet @JohanBoer wie Berni is. Ik zal het ongetwijfeld verkeerd hebben begrepen/gespeld.

**Comment by JohanBoer** [comment]
Helaas, ik weet ook niet wie Berni is.

**Comment by RvdKlip** [comment]
Ik denk Bernie Goedhart. Onze stelselspecialist, betrokken als stakeholder vanuit Rotterdam
