### ISSUE TITLE
Beschikbaarheid teamleden (@allen)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/BRK-Bevragingen#17]

**Comment by TCIMEddy** [comment]
- Vanuit Amsterdam Marcel nog een naam
- Vanuit Den Haag: Cathy en BRK Volgt 
- Drechtsteden: niet aanwezig
- VNG Frank/Johan Boer
- Jan Willem Kooi
- Kadaster (Lennart/Marianne)
- Rotterdam stakelholder
- Vicrea stakeholder

**Comment by CathyDingemanse** [comment]
> * Vanuit Amsterdam Marcel nog een naam
> * Vanuit Den Haag: Cathy en BRK Volgt
> * Drechtsteden: niet aanwezig
> * VNG Frank/Johan Boer
> * Jan Willem Kooi
> * Kadaster (Lennart/Marianne)
> * Rotterdam stakelholder
> * Vicrea stakeholder

BRK- en erfpachtdeskundige Den Haag: Rob van Alem

**Comment by MarcelMoerman** [comment]
Vanuit Amsterdam sluit Agustin Matilla Sanz aan, ik praat hem de week (17-12 > 21-12) bij over de inhoud en het project.

**Comment by JohanBoer** [comment]
Vanuit VNGRealisatie heb ik 12 uur per week ingepland. Dit is nog niet door de interne resource-planning geverifieerd.

**Comment by JanWillemKooi** [comment]
In principe ben ik 8u/w beschikbaar. Morgen kunnen Eddy en Wishal niet meedoen met de call. Ik zal de rol van Eddy waarnemen

**Comment by TCIMEddy** [comment]
@JanWillemKooi Volgens mij neem de taak over toch?

**Comment by JanWillemKooi** [comment]
Ja, dat klopt. Sterker nog, ik zit al in de call.

**Comment by JanWillemKooi** [comment]
Het team bestaat uit de volgende personen:

Cathy Dingemanse | Gemeente Den Haag | Product Owner
Jan Willem Kooi | VNG | Scrum Master
Johan Boer | VNG
Karin de Bourgraaf | Kadaster
Marianne Leferink | Kadaster
Lennart van Bergen | Kadaster
Hilde Vos | Kadaster
Marcel Moerman | Gemeente Amsterdam
Agustin Matilla Sanz | Gemeente Amsterdam
Mervin Lee | Gemeente Den Haag | SW leverancier
Marco Baars | Vicrea Solution
Remco Veenstra | Vicrea Solution
Kayo de Bakker | Process Five (SW leverancier Den Haag)

Als Stakeholders doen mee:
Brenda de Graaf | Gemeente Den Haag
Rob van Alem | Gemeente Den Haag
P van Wijnen | Gemeente Pijnacker-Nootdorp
Rob Ermaar | Gemeente Drechtsteden
FrankTuerlings | Gemeente Drehtsteden
Wishal Gokoel | VNG | Delivery manager
Robert Melskens | VNG | API beheer
