### ISSUE TITLE
Openstaande acties/communicatie/beslissingen binnen gemeenten

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/BRK-Bevragingen#19]
Met name binnen Den Haag en Drechtsteden als launching gemeenten. Actie vertegenwoordigers gemeenten

**To Do's

- [x] Budget regelen consumer (@CathyDingemanse)
- [x] Contract leverancier consumer Den Haag regelen (@CathyDingemanse) 
- [x] Inzet en planningsafspraken maken met leverancier (@CathyDingemanse )

**Comment by CathyDingemanse** [comment]
to do's vanuit Den Haag: 
Budget regelen consumer
Contract leverancier consumer Den Haag regelen
Inzet en planningsafspraken maken met leverancier
